/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { Vault } from '../../domain/entities';

/**
 * DataExportService:
 * Generates exportable reports and raw data files.
 */
export const DataExportService = {
  /**
   * Generates a clinical progress report in Markdown.
   */
  exportMarkdownReport(vault: Vault): string {
    const journal = vault.journal || [];
    const today = new Date().toLocaleDateString();
    
    let md = `# Lumina Clinical Report\n`;
    md += `Generated: ${today}\n\n`;
    
    md += `## 1. Profile Summary\n`;
    md += `- **User:** ${vault.profile.name}\n`;
    md += `- **Clinical Profile:** ${vault.profile.clinicalProfile || 'Unspecified'}\n`;
    md += `- **Total Sessions:** ${journal.length}\n`;
    md += `- **Discipline Level:** ${vault.stats.level}\n\n`;
    
    md += `## 2. Journal Highlights (Last 10)\n`;
    md += `| Date | Emotion | Intensity | Level | Distortions |\n`;
    md += `|------|---------|-----------|-------|-------------|\n`;
    
    journal.slice(0, 10).forEach(e => {
      md += `| ${e.date} | ${e.primaryEmotion} | ${e.intensity}/10 | L${e.level} | ${e.distortions?.join(', ') || '-'} |\n`;
    });
    md += `\n`;
    
    md += `## 3. Cognitive Patterns\n`;
    const distortionCounts: Record<string, number> = {};
    journal.forEach(e => {
      (e.distortions || []).forEach(d => {
        distortionCounts[d] = (distortionCounts[d] || 0) + 1;
      });
    });
    
    const sorted = Object.entries(distortionCounts).sort((a, b) => b[1] - a[1]);
    if (sorted.length > 0) {
      md += `Top cognitive distortions detected:\n`;
      sorted.slice(0, 5).forEach(([d, count]) => {
        md += `- **${d}:** ${count} occurrences\n`;
      });
    } else {
      md += `No cognitive patterns detected yet.\n`;
    }
    md += `\n`;
    
    md += `## 4. Strategic Objectives\n`;
    (vault.goals || []).forEach(g => {
      md += `- [${g.completed ? 'x' : ' '}] **${g.title}:** ${g.progress}% (${g.status})\n`;
    });
    
    md += `\n---\n*This report was generated by Lumina. It contains sensitive clinical data intended for therapeutic review.*`;
    
    return md;
  },

  /**
   * Generates a raw CSV of journal entries for analysis.
   */
  exportCSV(vault: Vault): string {
    const journal = vault.journal || [];
    let csv = `date,emotion,intensity,level,distortions,outcomeIntensity\n`;
    
    journal.forEach(e => {
      const distortions = (e.distortions || []).join('; ');
      csv += `${e.date},"${e.primaryEmotion}",${e.intensity},${e.level},"${distortions}",${e.outcomeIntensity}\n`;
    });
    
    return csv;
  },

  /**
   * Triggers a browser download of the content.
   */
  downloadFile(content: string, filename: string, mimeType: string) {
    const blob = new Blob([content], { type: mimeType });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = filename;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  }
};
